# Generated by Django 5.2.6 on 2025-09-14 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='prict',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='prict',
            new_name='price',
        ),
    ]
